### ISSUE TITLE
Ticketcache wahrscheinlich defekt

### ISSUE THREAD

**Issue by CE7** [minova-afis/aero.minova.core.application.system#150]
Wenn man in der Stundenerfassung ein Ticket erfassen möchte, wird immer als Antwort das Ticket: #52455 zurückgegeben. 
![Bildschirmfoto 2021-07-15 um 15 45 07](https://user-images.githubusercontent.com/20420898/125801932-9eddfd47-ffde-49f2-8e32-111f3888d3d4.png)

Angefragt wurde beispielsweise das Ticket: #18000

**Comment by CE7** [comment]
Nach dem Neustart konnten die Tickets nicht aufgelöst werden: 
![Bildschirmfoto 2021-07-15 um 16 13 17](https://user-images.githubusercontent.com/20420898/125802722-d40413e1-5308-4050-8440-bf372c92bfa8.png)

**Comment by splitcells** [comment]
Wir hatten heute den HTTP-Zugriff zum Trac blockiert,
wodurch das CAS auf dem QNAP auf die Tickets nichtmehr zugreiffen konnte.
Allerdings wurde in diesem Fall anscheinend, das letzte Ticket (aus dem Cache?) zurückgegeben,
anstatt einen Fehler zu bringen.
Dass sollten wir lösen.

Nach dem Neustart des CAS, wurde wie erwartet eine Fehlermeldung erzeugt.

**Comment by weber-minova** [comment]
Auf der produktiven Stundenerfassung gibt es noch gar keinen Cache. 
Ich denke eher, dass es sich um dieses Problem handelt, welches bereits gelöst wurde: https://github.com/minova-afis/aero.minova.trac/issues/3

Das produktive CAS wurde allerdings schon länger nicht mehr aktualisiert, weshalb diese Änderung auch noch nicht drin ist.
