### ISSUE TITLE
files/read nutzt Zip-Dateien anscheinend nicht.

### ISSUE THREAD

**Issue by splitcells** [minova-afis/aero.minova.core.application.system#160]
Der Cache wird somit nicht genutzt.
Dies passiert nur, wenn `files/zip` aufgerufen wird.

Ich denke, dass dies so nicht gewollt ist.

Zudem heisst die Test-Klasse des FilesController FileController.
Dass sollte man vereinheitlichen.

**Comment by weber-minova** [comment]
files/read wird nicht von der WFC Anwendung genutzt, die Anwendung fragt mit files/read nach den zip-Dateien.

**Comment by splitcells** [comment]
Dann werden wir es wohl in #163 etwas anpassen müssen.
