### ISSUE TITLE
JobExecuter

### ISSUE THREAD

**Issue by janiak-minova** [minova-afis/aero.minova.core.application.system#170]
Es soll einen JobExecuter geben, der aus der Anwendung angestoßen werden kann.

**Comment by splitcells** [comment]
- [ ] Event-Format für JobExecutor bestimmen.
- [ ] API für JobExecutor-Event erstellen.
- [ ] JobExecutor anpsrechen.
- [ ] Erweiterung als Plugin implementieren.

**Comment by CE7** [comment]
Die Anforderung an vom SIS 12 ist: 

- [ ] Birtreport erstellen (Rechnung) und per Mail an an Empfänger sende

**Comment by splitcells** [comment]
BIRT-Reports werden nicht über den JobExecutor erstellt:
* https://github.com/minova-afis/aero.minova.core.application.system/issues/171
* https://github.com/minova-afis/aero.minova.birt.report

An dem BIRT-Report ist die Kerstin dran.

**Comment by splitcells** [comment]
@janiak-minova Brauchen wir den JobExecutor noch für das SIS WFC?

**Comment by janiak-minova** [comment]
Da anscheinend weder BirtReports noch die Schnittstelle zum SAP über einen JobExecutor ausgeführt werden denke ich nicht.

**Comment by splitcells** [comment]
Man kann das Ticket ja später wieder aufmachen,
falls man den doch braucht.
