### ISSUE TITLE
Wo/wie können BIRT-Reports erstellt werden?

### ISSUE THREAD

**Issue by CE7** [minova-afis/aero.minova.core.application.system#171]
Ein Service der parallel zum CAS auf dem Server läuft. Der CAS kann dann auf diesen Service zugreifen und die generierte PDF an WFC übergeben. 

Hier können wir sicherlich mit Lars schnell fortschritte erzielen. Es handelt sich um eine Dienst/Service der aus der Eclipse-Welt stammt.

**Comment by weber-minova** [comment]
Die alte Implementierung ist im Minova Git unter git\minova\core\bundles\ch.minova.birt.report\
Ich habe hier zumindest schon einmal angefangen: https://github.com/minova-afis/aero.minova.birt.report

**Comment by splitcells** [comment]
Wir sollten erstmal den vorhanden Code migrieren damit die vorhanden Reports funktionieren:

- [ ] Neue BIRT-Abhängigkeiten aus Maven verwenden.
- [ ] Alte Klassen übernehmen und anpassen:
- [ ] 1. Die eigentliche Report-Generierung liegt anscheinend unter `ch.minova.birt.report.BirtReportGenerator` bzw. `ch.minova.ncore.print.*`. Diesen Code müssen wir portieren. Das liegt im ncore.
- [ ] 2. core\bundles\ch.minova.birt.report: enthält Aufruf für Report generierung. Hier müssen wir es an unsere Extension-Schnittstelle anpassen.

**Comment by weber-minova** [comment]
Dienst läuft auf publictest und erstellt PDFs.
API und Installation ist dokumentiert.
