### ISSUE TITLE
Groß/Kleinschreibung bei Rechten "deaktivieren"

### ISSUE THREAD

**Issue by weber-minova** [minova-afis/aero.minova.core.application.system#216]
Beim Testen der Masken ist aufgefallen, dass beim Überprüfen von Rechten auf Groß- und Kleinschreibung geachtet wird.
Das hat stark für Verwirrung gesorgt, da die Rechte ja in den Tabellen standen.

Besser wäre einfach beide .toLowerCase() zu setzten und dann zu vergleichen.

**Comment by splitcells** [comment]
Solange es keine starken Gründe gibt dafür,
würde ich es bevorzugen Funktionen zu vermeiden,
die zu Inkonsistenzen führen.
