### ISSUE TITLE
xpcorCheckGraduation ausführen, wenn Staffelsatzstufe geändert wurde

### ISSUE THREAD

**Issue by janiak-minova** [minova-afis/aero.minova.core.application.system#220]
Wenn an einer Staffelsatzstufe etwas geändert wurde (also xpcor[Insert,Update,Delete]GraduationStep aufgerufen) muss danach die Prozedur xpcorCheckGraduation in der gleichen Transaktion ausgeführt werden. Wenn diese nicht funktioniert muss die ganze Transaktion rückgängig gemacht werden.

**Comment by splitcells** [comment]
Der XSqlProcedureController soll so erweitert werden,
dass am Ende eines Aufrufs eine Listes von Prüfprozeduren implizit aufgerufen werden.
Diese Prozeduren haben keine Parameter.
Sobald eine Prüfprozedur einen Fehler hat, soll die gesamte Transaktion des Aufrufes rückgängig gemacht werden.

Folgendermaßen werden die Prüfprozeduren bestimmt:
* Das CAS hält sich ein Map vor die für jeden Prozeduren-Namen eine Menge(HashSet) von Prüfprozeduren-Namen enthält.
* Die Map wir aus `system-files/procedure-checks.properties` ausgelesen. Die Keys dürfen mehrmals mit unterschiedlichen Werten vorhanden sein.
* Beim starten liesst das CAS die properties-Datei aus und erstellt die entsprechende Map.
* Beim Ende des Aufrufs von XSqlProcedureController, soll für alle aufgerufenen Prozeduren die Prüfprozeduren in der Map nachgeschaut  werden.

**Comment by weber-minova** [comment]
Eintrag für genau diese KeyText-TransactionChecker-Kombi ist im Kundenproject im initTransactionChecker-Skript eingetragen.
