### ISSUE TITLE
SQL-Fehlermeldungen für WFC aufbereiten

### ISSUE THREAD

**Issue by weber-minova** [minova-afis/aero.minova.core.application.system#240]
Die Fehlermeldungen, welche von SQL-Prozeduren geworfen werden, haben folgendes Format: http://trac.minova.com/trac/minova/wiki/SQLMessages

Momentan werden diese als einfacher String in einer Zeile an das WFC gegeben, auch wenn Input-Variablen vorhanden sind (%s).

Beim Umsetzten soll darauf geachtet werden, dass an das WFC auch die @-Parameter geschickt werden (@s, @p, ect.), da z.B. die Properties (@p) extra aus einer Liste heraus gesucht und übersetzt werden müssen.

**Comment by janiak-minova** [comment]
Wunsch vom WFC: 

Die Fehlermeldung als Tabelle mit einer Zeile und 2 + Anzahl Parameter Spalten. 
- Als ersten Wert der Zeile kommt die eigentliche Meldung, Spaltenname egal
- Die nächstes kommen die eigentlichen Parameter, der Spaltenname ist entsprechend dem Typ z.B. `s`, `p`, ...
- Zuletzt kommt der Default Wert, der verwendet werden soll, wenn die eigentliche Meldung nicht übersetzt werden konnte, Spaltenname `DEFAULT`

Beispiel: Meldung im SQL-Code `'ADO | 25 | msg.sql.51103 @p tUnit.Description.16 @s kg | Einheit kann nicht in Einheit der Leistungsart umgerechnet werden'` 

Tabelle an WFC:
| Message | p | s | DEFAULT |
| ------------- | ------------- | ------------- | ------------- |
| msg.sql.51103 | tUnit.Description.16 | kg | Einheit kann nicht in Einheit der Leistungsart umgerechnet werden |
